### ISSUE TITLE
Not able to read sms using code

### ISSUE THREAD

**Issue by thoms6johny** [Seeed-Studio/GPRS_SIM900#16]
It never goes further than this statement on the serial moniter.
![gsm](https://cloud.githubusercontent.com/assets/25280549/22182733/d32ea83c-e0d2-11e6-957d-45010ec5d3f8.png)

**Comment by lanselambor** [comment]
@thoms6johny If you can send SMS than you can read SMS, try both tow examples.

**Comment by bte234** [comment]
I am also experiencing the same problem. I have sent the command "AT+CNMI=2,2,0,0,0" and have changed the baud rate to 19200 (which works fine when I use it to call, receive calls or send sms). I can read the message in the serial using uart to usb, but I cannot read SMS using the example code, either the loophandle or the smsread one. Calling, receiving calls or sending sms work fine.
![image](https://cloud.githubusercontent.com/assets/26082352/23397555/9be4a78a-fdcb-11e6-903f-c50976f4a9e6.png)
.

**Comment by Seedler1981** [comment]
I am also having the same problem.  SMSRead code intermittently works.  There seems to be no reason to it.  Sometimes it sees the messages, but most times it does not.  The messages are definitely there because if I just use AT commands through serial debug, everything works fine, and messages can be seen and received.  I believe it is something to do with the IsMessageUnread function in GPRS_ShielsArduino.cpp.  It does not seem to be indexing messages, I think.  Any ideas?

**Comment by ortegafernando** [comment]
see [https://github.com/Seeed-Studio/GPRS_SIM900/issues/19](https://github.com/Seeed-Studio/GPRS_SIM900/issues/19)
