### ISSUE TITLE
can't read sms sim800l

### ISSUE THREAD

**Issue by beryindo** [Seeed-Studio/GPRS_SIM900#19]
can't read sms sim800l. this support ussd?

**Comment by ortegafernando** [comment]
Hi, I have reopened it because I have a mistake in the library isSMSunread function.

Both sendSMS and readSMS configure SMS to text mode.
```
AT+CMGF=1
```

And after that, they send AT commands to send, read or whatever.

isSMSunread doesn't. It will have to send AT+CMGF=1 and wait 1000 miliseconds, and after that, call to AT+CMGL="REC UNREAD",1

We could also configure always AT+CMGF=1 inside init function. (or you could also configure it forever (SIM900/SIM800 eeprom) by AT+CMGF=1 plus AT&W

**PLEASE, TELL ME IF YOU PREFER AT+CMGF in the init function, or in each other individual functions**.  (I prefer in init function, so we dont need to wait always 1000 miliseconds in the other functions)

I have a much more developed SIM900 library, wait a few days for a big update.

Thanks.

**Comment by ortegafernando** [comment]
@lanselambor  Please, tell me your opinion, Do you prefer also in the INIT function ?

**Comment by ortegafernando** [comment]
@KillingJacky Also, Jack, please tell me your opinion. Thanks

**Comment by ortegafernando** [comment]
I have added a new pull request [https://github.com/Seeed-Studio/GPRS_SIM900/pull/31](https://github.com/Seeed-Studio/GPRS_SIM900/pull/31)
